// words.js — LEXIS word pool, grouped by difficulty (length)
const ALL_WORDS = [
  // 2-letter
  'be','do','go','hi','if','in','is','it','me','my','no','of','ok','on','or','to','up','us','we',
  // 3-letter
  'ace','add','ago','aid','aim','air','all','and','ant','any','arc','arm','art','ask','awe',
  'bad','bag','ban','bar','bat','bay','bed','big','bit','box','boy','bud','bug','bus','but','buy',
  'can','cap','car','cat','cry','cup','cut','day','did','dig','dim','dot','dry','due',
  'ear','eat','egg','ego','end','era','eye','far','fat','fee','few','fit','fix','fly','fog','for','fox','fun','fur',
  'gap','gas','get','god','got','gun','gut','guy','gym','had','has','hat','hay','her','him','hip','his','hit','hop','hot','how','hug',
  'ice','ill','ink','ion','jar','jaw','jet','job','jog','joy','jug','key','kid','kit',
  'lab','lag','lap','law','lay','led','leg','let','lid','lip','lit','log','lot','low',
  'mad','map','may','mob','mom','mop','mud','mug','nap','net','new','not','now','nut',
  'oak','odd','off','oil','old','one','opt','orb','ore','out','owl','own',
  'pad','pal','pan','pat','paw','pay','pen','pet','pie','pig','pin','pit','pod','pop','pot','pub','pun','put',
  'rag','ram','ran','rap','rat','raw','ray','red','rid','rim','rip','rob','rod','rot','row','rub','rug','run',
  'sap','saw','say','set','sew','shy','sin','sip','sit','six','sky','sob','son','spa','spy','sub','sum','sun',
  'tab','tan','tap','tar','tax','tea','ten','tie','tin','tip','toe','top','toy','try','tug','two',
  'use','van','vat','via','vow','wag','war','was','wax','way','web','wed','wet','who','why','win','wit','won',
  'yam','yep','yet','you','zap','zen','zip','zoo',
  // 4-letter
  'able','acid','aged','area','army','away','baby','back','ball','band','bank','base','bath','bear','beat',
  'bell','belt','best','bike','bill','bind','bird','bite','blow','blue','boat','bold','bolt','bomb','bond',
  'bone','book','boom','boot','born','bowl','bulk','bull','bump','burn','bust','busy','byte',
  'cage','cake','call','calm','camp','card','care','cart','case','cash','cast','cave','cell','cent','chat',
  'chef','chip','chop','city','clap','clip','club','clue','coal','coat','code','coin','cold','comb','come',
  'cone','cook','cool','copy','cord','cost','crew','crop','cube','curb','cure','curl',
  'damp','dare','dart','dash','data','date','dawn','dead','deal','dear','debt','deck','deed','deep','dent',
  'desk','dial','dice','diet','disk','dive','dock','dome','done','door','dose','down','draw','drop','drum',
  'dune','dusk','dust','duty',
  'each','edge','else','epic','even','ever','exam','exit',
  'face','fact','fail','fair','fake','fall','fame','farm','fast','fate','fear','feat','feel','fill','film',
  'find','fine','fire','firm','fish','fist','flag','flat','flip','flow','foam','fold','fond','food','fool',
  'foot','form','fort','four','free','frog','from','fuel','full','fuse',
  'gain','game','gang','gaze','gear','gift','girl','give','glad','glow','glue','goal','gold','golf','good','grab',
  'grid','grin','grip','grow','gulf',
  'hack','hail','hair','half','hall','hand','hang','hard','harm','have','heal','heap','heat','heel','held',
  'helm','help','here','hero','hide','high','hill','hint','hire','hold','hole','home','hood','hook','hope',
  'horn','host','hour','hunt',
  'icon','idea','inch','into','iron','isle','item',
  'jack','jade','jail','jump','just','keen','keep','kick','kill','kind','king','knee','know',
  'lace','lack','lake','lamp','land','lane','last','late','lead','leaf','lean','leap','left','lend','lens',
  'less','lick','life','lift','like','lime','line','link','lion','list','live','load','loan','lock','lone',
  'long','look','lord','lose','loss','loud','love','luck','lung',
  'made','mail','main','make','mall','mare','mark','mask','mass','mate','math','maze','meal','mean','meat',
  'meet','melt','menu','mild','mile','milk','mill','mind','mine','mint','miss','mist','mode','mold','monk',
  'moon','more','most','move','much','must','myth',
  'nail','name','neon','nest','next','nice','nine','node','none','noon','norm','note','noun',
  'once','only','open','oven','over',
  'pace','pack','page','pain','pair','pale','palm','park','part','pass','past','path','peak','peer','pest',
  'pick','pile','pink','pipe','plan','play','plot','plug','plus','poem','poll','pond','pool','pore','port',
  'pose','post','pour','pray','prey','pull','pump','pure','push',
  'race','rack','rage','rain','rake','rank','rave','read','real','reap','rear','rely','rent','rest','rice',
  'rich','ride','ring','riot','rise','risk','road','roam','roar','rock','role','roll','room','rope','rose',
  'rude','rule','rush',
  'safe','sail','sake','sale','salt','same','sand','sang','save','scan','seal','seat','seed','seek','seen',
  'self','sell','send','sign','silk','sing','sink','site','size','skin','slam','slim','slip','slow','snap',
  'soar','sock','soil','sole','song','soon','sore','sort','soul','soup','spin','spit','spot','star','stay',
  'step','stir','stop','stun','such','suit','sung','sure','sway','swim','sync',
  'tail','tale','talk','tall','task','tell','tend','tent','term','test','text','than','that','them','then',
  'they','thin','this','tile','time','tiny','tire','told','toll','tone','took','torn','toss','tour','town',
  'trap','tree','trek','trim','trip','true','tube','tune','turf','turn','twin','type',
  'undo','unit','upon','used','vain','vary','vast','veil','vein','vent','verb','very','vest','view','vine',
  'void','vote','wade','wake','walk','wall','want','ward','warm','warn','warp','wash','wave','weak','wear',
  'weed','week','well','went','were','west','wide','wild','will','wind','wine','wing','wire','wish','with',
  'wolf','wood','wool','word','wore','work','wrap',
  'yard','yarn','year','yell','your','zero','zest','zone',
  // 5-letter
  'abbey','abort','about','above','abuse','acute','adapt','admit','adopt','adult','after','again','agent',
  'agree','ahead','alarm','album','alert','alien','align','alive','alone','along','alter','amaze','amend',
  'ample','angel','anger','angle','angry','ankle','apart','apple','apply','arena','argue','arise','array',
  'aside','asset','atlas','audit','avert','avoid','awake','award','aware',
  'badge','baker','basic','basis','batch','beach','began','begin','being','below','bench','berry',
  'black','blade','blame','blank','blast','blaze','bleed','blend','bless','blink','block','blood','bloom',
  'board','boast','bonus','boost','bound','brain','brand','brave','break','breed','brick','bride','brief',
  'brink','brisk','broad','broke','brook','brown','brush','build','built','bunch','burst',
  'cabin','canal','candy','cargo','cause','cease','chain','chair','chaos','charm','chart','chase','cheap',
  'check','cheek','cheer','chest','chief','child','chill','choir','civic','civil','claim','class','clean',
  'clear','clerk','click','cliff','climb','clock','clone','close','cloth','cloud','coach','coast','cobra',
  'comic','coral','couch','count','court','cover','crack','craft','crane','crash','crawl','crazy','cream',
  'creek','crime','crisp','cross','crowd','crown','crush','crypt','curve',
  'daily','dance','decay','delta','dense','depot','depth','dirty','disco','dizzy','dodge','doubt','draft',
  'drain','dwarf','dying',
  'eagle','early','earth','elect','elite','email','empty','enemy','enjoy','enter','entry','equal','equip',
  'erode','error','essay','event','every','exact','exist','extra',
  'fable','faith','fancy','fatal','fault','feast','fence','fever','field','fifth','fight','final','first',
  'fixed','flame','flare','flash','fleet','flesh','flock','floor','flour','fluid','flute','force','forge',
  'forum','fraud','fresh','front','frost','fruit','fully','fungi','funny',
  'giant','given','glare','glass','glide','gloom','glory','gloss','glove','grace','grade','grain','grand',
  'grant','grasp','grass','grave','great','greed','greet','grief','grind','groan','gross','group','grove',
  'guard','guess','guide','guild','guilt','gusto',
  'habit','happy','harsh','haven','heart','heavy','hedge','herbs','hippo','hoard','hobby','honor','horse',
  'hotel','hound','house','humor','hurry',
  'ideal','image','imply','inbox','index','inner','input','irate',
  'joker','jolly','judge','juice','juicy','jumpy','karma','knack','knife','known',
  'label','lance','large','laser','later','layer','learn','lease','least','leave','ledge','legal','level',
  'light','limit','liver','local','lodge','logic','loose','lover','lower','lucky','lunar','lyric',
  'magic','major','maker','manor','maple','march','marry','match','mayor','media','mercy','merit','metal',
  'meter','minor','minus','model','money','month','moral','motel','motor','mount','mouse','mouth','muddy',
  'music','naive','nerve','never','night','ninja','noble','noise','north','notch','novel','nurse',
  'occur','offer','often','olive','orbit','order','other','outer','ozone',
  'panic','paper','party','pasta','pause','peace','pearl','penny','perch','phone','photo','piano','piece',
  'pilot','pinch','pizza','pixel','place','plain','plane','plant','plate','plaza','pluck','plume','point',
  'polar','porch','pouch','power','price','pride','prime','print','prior','prize','probe','proof','prose',
  'proud','pulse','pupil','purse','queen','query','quest','quick','quiet','quota','quote',
  'radar','radio','raise','rally','ranch','rapid','ratio','reach','rebel','reign','relax','remix','repay',
  'reply','reset','ridge','rifle','risky','rival','river','rogue','rough','round','route','royal','ruler','rural',
  'sadly','saint','salad','sauce','savvy','scale','scene','scope','score','scout','sense','serve','seven',
  'shade','shaft','shake','shame','shape','share','shark','sharp','shelf','shell','shift','shine','shirt',
  'shock','shore','short','shout','shown','siege','sight','silly','since','sixth','sixty','skill','skull',
  'slice','slide','slope','smart','smash','smell','smile','smoke','snack','snake','sneak','solar','solve',
  'sorry','south','space','spare','speak','spear','speed','spend','spill','spine','spoke','spray','squad',
  'stack','stage','stain','stand','stare','start','state','steal','steam','steel','stern','stick','still',
  'stomp','stone','stood','store','storm','story','straw','strip','stuck','study','stuff','stump','style',
  'sugar','suite','sunny','super','surge','swarm','swear','sweat','sweep','sweet','swift','swipe','sword','swung',
  'table','taken','tally','taste','teach','tease','teeth','tempo','tense','thank','thick','third','thorn',
  'three','throw','thumb','tiger','tight','title','toast','token','topic','torch','total','touch','toxic',
  'track','trade','trail','train','trash','treat','trend','trial','trick','tried','troop','truce','truly',
  'trunk','trust','truth','tulip','twice','twist','tying',
  'ultra','union','unite','until','upper','upset','urban','usual','utter',
  'vague','value','valve','vapor','vault','vigor','viral','virus','visit','vital','vivid','vocal','voice','vowel',
  'wager','wagon','waltz','waste','watch','water','weary','weave','wedge','weigh','weird','where','which',
  'while','white','whole','whose','wield','witch','witty','world','worry','worse','worst','worth','wound',
  'write','wrong','yacht','yearn','yield','young','youth','zebra','zippy',
  // 6-letter
  'absent','accent','access','accord','action','active','actual','adjust','advise','affect','afford','agency',
  'almost','always','anchor','annual','answer','anthem','anyway','appear','around','arrest','arrive','aspect',
  'assure','attach','attack','attain','attend','author','autumn',
  'ballet','barely','battle','beauty','before','behind','belief','belong','beyond','bitter','border','bottle',
  'bounty','breath','breezy','bridge','bright','broker','bronze','bubble','bucket','budget','bullet','bunker',
  'burden','burger','button',
  'cactus','camera','cancel','candle','canvas','canyon','carbon','castle','casual','cattle','cavern','cement',
  'center','chance','change','charge','cherry','choice','chrome','circle','circus','client','closet','coffee',
  'colony','column','commit','common','corner','cotton','couple','crafty','create','credit','crisis','cursor','custom',
  'dagger','damage','dancer','danger','dazzle','decide','defend','define','delete','deploy','deputy','desert',
  'design','detail','detect','differ','direct','divide','dollar','domain','drawer','driven',
  'easily','effect','effort','either','emerge','empire','enable','engage','enough','entire','escape','estate',
  'evolve','exceed','except','expand','expert','export','extend',
  'famine','filter','finger','finish','flavor','flight','flower','follow','forget','formal','frozen','future',
  'gather','gentle','gifted','global','goblin','gotten','greedy','grieve','grudge','growth','guitar',
  'happen','harbor','hardly','health','heaven','helmet','hidden','highly','hinder','honest','horror','hunter','hustle',
  'ignore','impact','import','income','indeed','injury','insect','insist','intend','invest','island',
  'jigsaw','joyful','junior','jungle','kidnap','killer','kitten',
  'ladder','launch','lessen','letter','living','lonely',
  'manage','manner','marble','master','matter','member','memory','mentor','method','middle','mirror','modern',
  'modest','module','moment','monkey','mortal','motive','muscle','mutual','mystic',
  'narrow','nation','nature','nearly','needle','nimble','normal','notion','number',
  'obtain','origin','output','palace','pardon','parent','patrol','pencil','people','period','permit','person',
  'pillar','pirate','planet','player','pledge','plenty','pocket','policy','portal','prison','proper','proven',
  'public','punish','purple','pursue','puzzle',
  'rabbit','raging','random','rather','really','reason','recall','reduce','reform','refund','refuse','regret',
  'remain','remote','render','repeat','rescue','resist','resort','result','return','reveal','review','rhythm',
  'riddle','robust','rocket','rotate','rubber','runner',
  'sacred','safety','sample','savage','scheme','school','screen','search','second','secret','sector','secure',
  'select','senior','settle','severe','shadow','silver','simple','single','slight','smooth','social','source',
  'speech','sphere','spiral','splash','spoken','sprint','stable','statue','steady','strain','street','stress',
  'strict','string','strong','stumble','submit','subtle','sunset','symbol','system',
  'tackle','talent','target','tender','thanks','thread','threat','thrive','timber','toggle','travel','trophy',
  'tumble','tunnel','tycoon',
  'unable','unfair','unfold','unique','unlock','update','useful',
  'victim','visual','volume','wander','warmth','weapon','weekly','window','winter','wisdom','within','wonder',
  'wooden','worthy',
  // 7-letter
  'abstain','achieve','acquire','adamant','adverse','ancient','antenna','anxious','arrange','attract','average','awesome','awkward',
  'balance','banking','bargain','barrier','battery','because','bedroom','between','blossom','bravery','brother','brought',
  'cabinet','captain','capture','catalog','ceiling','certain','chapter','charity','classic','cluster','compact','company',
  'compass','compete','complex','concern','confuse','connect','contain','context','control','convert','correct','corrupt',
  'courage','current',
  'defense','deliver','density','deserve','desktop','destiny','digital','dilemma','display','distant','disturb','dormant','dynasty',
  'economy','element','engaged','examine','excited','express','extreme',
  'fearful','fertile','fiction','focused','foolish','foreign','forever','fortify','forward','frantic','freedom','furious',
  'general','genuine','glacier','glowing','gorilla','gravity','growing',
  'harmful','harvest','helpful','history','hostile','however','humming','hunting',
  'illegal','illness','imagine','impress','improve','include','initial','instead','intense','involve',
  'jealous','keeping','knowing','lantern','largely','lasting','leading','learned','leaving','leisure','library','limited',
  'magical','maximum','meaning','meeting','message','minimum','missing','mission','mixture','monitor','morning',
  'nothing','nowhere','nuclear',
  'obvious','offense','ongoing','opening','opinion','optimal','outline','outside','overall',
  'painful','parking','partial','passing','pattern','penalty','percent','perfect','physics','picture','playing',
  'popular','portion','present','primary','private','problem','process','product','program','project','promote',
  'protect','provide','purpose',
  'quickly','reading','reality','recover','regular','related','release','replace','reserve','respect','respond',
  'restore','reverse',
  'sailing','satisfy','scatter','science','section','serious','serving','session','setting','sharing','shelter',
  'showing','singing','skilled','soldier','somehow','sorting','special','species','stadium','station','storage',
  'stretch','student','subject','success','suggest','surface','survive','suspect',
  'talking','testing','texture','theatre','through','tonight','trading','triumph','trouble','turning',
  'unclear','unified','unknown','unusual','viewing','village','violent','visible','waiting','walking','wanting',
  'warfare','warning','washing','wealthy','western','whether','willing','winning','without','working','writing',
  // 8-letter
  'absolute','abstract','accurate','activist','addition','adoption','advanced','affected','alliance','allowing',
  'although','analysis','animated','argument','assembly','assuming','attached','audience',
  'backfire','balanced','becoming','behavior','betrayal','blackout','blessing','blocking','boundary','breakout',
  'bringing','building',
  'calendar','campaign','capacity','catching','cautious','centered','champion','changing','charging','checking',
  'choosing','cleaning','clearing','climbing','combined','commerce','complete','composed','computer','conclude',
  'conflict','confused','constant','consumer','continue','convince','coverage','creating','crossing','cultural',
  'database','daughter','deadline','decision','decrease','defeated','delivery','demanded','deployed','designer',
  'detailed','discover','disorder','distance','division','dominant','doubtful','download','dramatic',
  'earnings','educated','election','emerging','employed','encoding','enormous','entirely','entrance','equality',
  'evaluate','everyone','evidence','exceeded','exchange','exercise','extended',
  'featured','feedback','festival','fighting','findings','flawless','floating','flourish','followed','formally',
  'frequent','function',
  'generate','governed','guidance','handling','hardware','helpless','heritage','honestly',
  'identify','illusion','imagined','impacted','included','industry','informed','innocent','inspired','instinct',
  'integral','intended','interest',
  'judgment','language','launched','learning','leverage','lifetime','lighting','limiting',
  'majority','manifest','managing','matching','material','measured','merchant','midnight','military','mindless',
  'moderate','momentum','movement','multiple',
  'negative','neighbor','networks','normally','obstacle','occasion','official','offshore','operator','optimize',
  'original','overcome',
  'peaceful','personal','planning','platform','positive','practice','precious','prepared','presence','previous',
  'priority','probably','progress','promised','proposal','protocol','provided',
  'realized','received','reducing','referred','reformed','regional','released','remained','removing','reported',
  'research','resolved','resource','restored','resulted','revealed',
  'scenario','schedule','security','selected','separate','sequence','shortage','simulate','software','solution',
  'speaking','specific','spectrum','spending','standard','standing','strategy','strength','striking','strongly',
  'struggle','stunning','suddenly','superior','survival',
  'tailored','targeted','teaching','template','terminal','thinking','together','training','traveled','trending',
  'ultimate','uncommon','unlikely','unstable','upcoming',
  'valuable','verified','virtually','warriors','watchful','whatever','willpower','wireless','wondered','woodland','workshop'
];

// Word length ranges per level
const LEVEL_WORD_LENGTHS = [
  [2, 3],   // Level 1
  [3, 4],   // Level 2
  [4, 5],   // Level 3
  [5, 6],   // Level 4
  [6, 7],   // Level 5
  [7, 8],   // Level 6
  [8, 9],   // Level 7
  [9, 10],  // Level 8
  [10, 12], // Level 9
  [12, 99]  // Level 10
];

function getWordPool(level) {
  const [minLen, maxLen] = LEVEL_WORD_LENGTHS[Math.min(level - 1, LEVEL_WORD_LENGTHS.length - 1)];
  return ALL_WORDS.filter(w => w.length >= minLen && w.length <= maxLen);
}
